In [2]:
import numpy as np

In [3]:

# Create a 1D array
array = np.array([1, 2, 3, 4, 5])
print("1D Array:", array)

1D Array: [1 2 3 4 5]


In [4]:
# Create a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(array_2d)

2D Array:
[[1 2 3]
 [4 5 6]]


In [5]:
# Perform basic arithmetic operations
sum_array = array + 5
print("Sum Array:", sum_array)

Sum Array: [ 6  7  8  9 10]


In [6]:
# Element-wise multiplication
mult_array = array * 2
print("Multiplied Array:", mult_array)

Multiplied Array: [ 2  4  6  8 10]


### Examples
- This repository includes a variety of examples demonstrating different NumPy functionalities. Below are some highlighted examples:

    - Array Creation and Manipulation
    - Mathematical Operations
    - Statistical Operations
    - Linear Algebra

### Array Creation and Manipulation

**Exercise 1: Creating Arrays**
1. Create a 1D array of integers from 1 to 10.
2. Create a 2D array of shape (3, 3) filled with random integers from 0 to 9.
3. Create a 3D array of shape (2, 3, 4) filled with ones.

**Exercise 2: Array Indexing and Slicing**
1. Extract the first three elements from the 1D array created in Exercise 1.
2. Extract the second row from the 2D array.
3. Extract the first two elements from each row of the second depth layer in the 3D array.

**Exercise 3: Array Reshaping and Flattening**
1. Reshape the 1D array into a 2D array of shape (2, 5).
2. Flatten the 2D array back into a 1D array.
3. Reshape the 3D array into a 2D array of shape (6, 4).

In [8]:
import numpy as np

# Exercise 1
array_1d = np.arange(1, 11)
print("1D Array:", array_1d)

1D Array: [ 1  2  3  4  5  6  7  8  9 10]


In [9]:
array_2d = np.random.randint(0, 10, (3, 3))
print("2D Array:\n", array_2d)

2D Array:
 [[3 2 3]
 [2 2 3]
 [8 1 5]]


In [10]:
array_3d = np.ones((2, 3, 4))
print("3D Array:\n", array_3d)

3D Array:
 [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [12]:
# Exercise 2
first_three_elements = array_1d[:3]
print("First three elements:", first_three_elements)
second_row = array_2d[1, :]
print("Second row:", second_row)
second_layer_elements = array_3d[1, :, :2]
print("First two elements of the second layer:\n", second_layer_elements)


First three elements: [1 2 3]
Second row: [2 2 3]
First two elements of the second layer:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
# Exercise 3
reshaped_2d = array_1d.reshape(2, 5)
print("Reshaped 2D array:\n", reshaped_2d)

Reshaped 2D array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
flattened_array = reshaped_2d.flatten()
print("Flattened array:", flattened_array)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [16]:
reshaped_3d_to_2d = array_3d.reshape(6, 4)
print("Reshaped 3D to 2D array:\n", reshaped_3d_to_2d)

Reshaped 3D to 2D array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Mathematical Operations

**Exercise 1: Basic Arithmetic Operations**
1. Create two 1D arrays and perform element-wise addition, subtraction, multiplication, and division.
2. Perform the same operations on 2D arrays of shape (2, 3).

**Exercise 2: Universal Functions (ufuncs)**
1. Apply the `np.sqrt` function to a 1D array of squared integers.
2. Apply the `np.exp` function to a 2D array of random floats between 0 and 1.

In [17]:
# Exercise 1
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([5, 4, 3, 2, 1])
addition = array_a + array_b
print("Element-wise addition:", addition)
subtraction = array_a - array_b
print("Element-wise subtraction:", subtraction)
multiplication = array_a * array_b
print("Element-wise multiplication:", multiplication)
division = array_a / array_b
print("Element-wise division:", division)

Element-wise addition: [6 6 6 6 6]
Element-wise subtraction: [-4 -2  0  2  4]
Element-wise multiplication: [5 8 9 8 5]
Element-wise division: [0.2 0.5 1.  2.  5. ]


In [18]:
array_2d_a = np.array([[1, 2, 3], [4, 5, 6]])
array_2d_b = np.array([[6, 5, 4], [3, 2, 1]])
addition_2d = array_2d_a + array_2d_b
print("2D Element-wise addition:\n", addition_2d)
subtraction_2d = array_2d_a - array_2d_b
print("2D Element-wise subtraction:\n", subtraction_2d)
multiplication_2d = array_2d_a * array_2d_b
print("2D Element-wise multiplication:\n", multiplication_2d)
division_2d = array_2d_a / array_2d_b
print("2D Element-wise division:\n", division_2d)

2D Element-wise addition:
 [[7 7 7]
 [7 7 7]]
2D Element-wise subtraction:
 [[-5 -3 -1]
 [ 1  3  5]]
2D Element-wise multiplication:
 [[ 6 10 12]
 [12 10  6]]
2D Element-wise division:
 [[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]


In [19]:
# Exercise 2
squared_array = np.array([1, 4, 9, 16, 25])
sqrt_array = np.sqrt(squared_array)
print("Square roots:", sqrt_array)
random_floats = np.random.rand(2, 3)
exp_array = np.exp(random_floats)
print("Exponential of random floats:\n", exp_array)

Square roots: [1. 2. 3. 4. 5.]
Exponential of random floats:
 [[1.9686739  2.20112453 1.62190299]
 [1.23042738 1.81040577 1.12640807]]
